name: called workflow
on:

 workflow_call:
 
jobs: 
 
  build:
     runs-on: ubuntu-latest
     env: 
      my-variable: ${{ needs.MyJobId.outputs.MyVariable }}
      ref: ${{ github.GITHUB_REF_NAME }}
     
     steps:
         - name: step-1
           run: |
              echo $hostname
              echo $UID
         - name: step-2
           run: |
               echo "trying to be called workflow" 
