##caller workflow

name: reusable workflow
on: 
 workflow_dispatch:
jobs: 
  caller_job:
     runs-on: ubuntu-latest
     steps:
         - name: script
           run: echo Hello,world
  calling_called:
     uses: sendevenkatesh/demo/ .github/workflows/called.yml@main
