name: called workflow
on: 
 workflow_call:
jobs: 
  build:
     runs-on: ubuntu-latest
     env: 
        branch_name: main
     steps:
         - name: step-1
           run: |
              echo $hostname
              echo $UID
         - name: step-2
           run: |
               echo "trying to be called workflow" 
