name: Fortify ScanCentral SAST Scan
on:
  workflow_dispatch:
  push:
        branches: [main]
  pull_request:
        branches: [main]
jobs:                                                  
  Fortify-SAST:
    runs-on: ubuntu-latest 
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
     
      #- run: git checkout HEAD^2
       # if: ${{ github.event_name == 'pull_request' }} 

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14

      ### Set up Fortify ScanCentral Client ###
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1   
        with:
          version: 21.2.0                                     
          client-auth-token: ${{ secrets.CLIENT_AUTH_TOKEN }}  
      ### Run Fortify ScanCentral Client ###
      
      - name: Perform SAST Scan
        run: scancentral -url ${SC_CONTROLLER_URL} start 
             $BUILD_OPTS -upload -application $APPLICATION -version $VERSION -uptoken $SSC_UPLOAD_TOKEN
        env:                                            
          SC_CONTROLLER_URL: ${{ secrets.SC_CONTROLLER_URL }}
          SSC_UPLOAD_TOKEN: ${{ secrets.SSC_UPLOAD_TOKEN }}
          APPLICATION: "My Application"
          VERSION: "1.0"
          BUILD_OPTS: "-bt mvn"

      ### Archive ScanCentral Client logs on failure ###
      - name: Save ScanCentral Logs
        uses: actions/upload-artifact@v2                
        if: failure()
        with:
           name: scancentral-logs
           path: ~/.fortify/scancentral/log
