name: ci for java 
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  
  # Allows external webhook trigger
  repository_dispatch:
    types: [webhook]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          mkdir venky
          touch file1
      - name: Webhook
        run: |
         curl \
         -H "Accept: application/json" \
         https://api.github.com/sendevenkatesh/demo/dispatches
          
          





