name: ci for java 
on: 
  push: 
    branches: [dev, main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          mkdir venky
          touch file1
      - shell: bash
        run: |
          expr 1 + 1 > output.log

  release:
    runs-on: ubuntu-latest
    steps:
      - name: create folder release
        run: |
         mkdir release
         



