name: ci for java 
on: 
  push: 
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          mkdir venky
          touch file1
          
          





